name: Take a snapshot of budget data

on:
  # Run every hour 
  schedule:
    - cron: "*/10 * * * *"

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Run budget data script
        run: |
          source("iati_marker.R")
        shell: Rscript {0}
      - name: Commit new file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
