name: Take a snapshot of budget data

on:
  # Run every X 
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
      - name: Query dependencies
        run: |
          install.packages('data.table')
          install.packages('dotenv')
          install.packages('httr')
          install.packages('dplyr')
          install.packages('rstudioapi')
      - name: Run budget data script
        run: |
          source("iati_marker.R")
        shell: Rscript {0}
      - name: Commit new file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
