name: Take a snapshot of budget data

on:
  # Run every day at 12am
  schedule:
    - cron: "0 0 * * *"
  # workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: set env
        run: |
          echo "PA_TOKEN=${{ secrets.PA_TOKEN }}" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Run budget data script
        run: |
          source("iati_marker.R")
        shell: Rscript {0}
      - name: Commit new file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
